language: node_js
node_js:
  - "8"

install:
  - npm install
  - npm install -g nyc codeclimate-test-reporter
script: nyc ./node_modules/mocha/bin/_mocha
addons:
  code_climate:
    repo_token: f7ac595a649faf65306c0eb694d875d8dea65e0ac644f07bb7e7599945098448
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
